### PR TITLE
Remove extra \

### PR DESCRIPTION
**Pull request by IvanCCO**

### CODE REVIEW

**Comment by IvanCCO** [comment]
I tested before to see if nothing breaks

**Comment by claytonjhamilton** [comment]
Hello and thank you for be willing to contribute @IvanCCO!

The README.md file is overwritten at each refresh with the template found in the `templates/main.html` file. If you would like to remove that slash (and have it stay removed) you'll want to remove it from the template.

If you're interested in making the change yourself for practice please update your PR. Otherwise, I appreciate your time in pointing out this improvement and can make the update myself.

**Comment by IvanCCO** [comment]
Hello, thanks for the comment, sure I will update my PR with the right fix.

**Review by claytonjhamilton — APPROVED** [review]
Looks great! Thank you

**Pull request merged**
